// v6.1.1588
(function(l,h,t,F,O,w,s,A,ga,ha,ia,v,S,D,T,u,ja,U){function V(a,b,c){if(!a)for(a in m)return m[a];if(m[b||a])return m[b||a];var d=new ka(a);c&&d.ia();return m[b||a]=d}function ta(a,b){return function(){a.call(b)}}function E(a){return"object"==typeof a}function ua(){for(var a=32,b="";a--;)b+=(0|16*O.random()).toString(16);return b}function B(a,b,c,d){var e;(e=a.addEventListener)?e.call(a,b,c,0):a.attachEvent(d||"on"+b,c)}function r(a,b,c){return function(){a(b,c)}}function C(a,b){for(var c in a)a.hasOwnProperty(c)&&
a[c]!==n&&b(a[c],c)}function W(a){var b=[];C(a,function(a,d){b.push(ga(d)+"="+ga(a))});return b.join("&")}function G(a,b){if(!a)throw Error(b);}function va(a){var b={};C(a,function(a,d){b[d]=a});return b}function la(a,b){C(a,function(c,d){E(c)&&(b["cp."+d]=W(c),a[d]=n)});b.cp=W(a)}function H(a,b,c,d){if(a&&a.call)a();else if(/^GSN-.*-.$/.test(a))b!==""+b&&(c=b,b=0),V(a,b,c||c===n);else if(/^_/.test(a))P[a]&&P[a](b,c),delete P[a];else{a=a[v](".");var e;1<a[D]&&(e=a.shift());a=a[0];var k={usecookies:1,
anonymizeip:2,visitorname:3,username:3,statuscode:5,cookiedomain:6,trackparams:7,trackhash:8,tracklocal:9,referrer:10,visitorid:13,visitor:4,clientid:11,auth:14,props:4,properties:4},f=function(a,b,c){e?m[e].s(a,b,c):C(m,function(d){d.s(a,b,c)})};if(/transaction$/i.test(a))return wa(e,b,c,d);if("get"==a)return c=k[(b+"")[T]()]||b,e?d=m[e].g(c):C(m,function(a){d=a.g(c)}),d;"set"==a?(a=(b+"")[v]("."),b=a.shift(),f(k[b[T]()]||b,c,a.join("."))):"track"==a?J(X,e,b,c,d):"event"==a?J(Y,e,b,c,d):"cancel"==
a?J(function(){this.F()},e):"noCookies"==a?f(1,0):"anonymizeIP"==a?f(2,1):"tag"==a?f(3,b):"load"==a?b&&b():"auth"==a?f(14,b):"identify"==a?J(xa,e,b,c,d):"alias"==a?f(13,b):"unidentify"==a?f(13):"props"!=a&&"properties"!=a||f(4,b)}}function ma(a,b,c){var d=a.h=a.h||{},e={};G(b||E(c),"Not an object");b?d[b]=e[b]=c:e=d=a.h=c;!a.da&&a.O&&(a.da=s(function(){na(a)},100))}function Z(a,b){function c(a){return"expires="+(new w(a)).toGMTString()+";"}var d="path=/;",e=a.g(6);e&&(d+="domain="+e+";");return{r:function(e,
f){a.g(1,1)&&(h.cookie=e+"="+f+";"+c(+new w+(b?6E10:6E4))+d)},o:function(b){if(a.g(1,1))return(h.cookie.match("(^|;)\\s*"+b+"=([^;]*)")||[])[2]||n},G:function(a){h.cookie=a+"=;"+c(0)+d}}}function J(a,b,c,d,e){b?a.call(m[b],c,d,e):C(m,function(b){a.call(b,c,d,e)})}function ka(a){var b=this;b.na=0;var c=[];c[12]=b.b=a;b.s=function(a,d,f){4==a&&(ma(b,f,d),d=b.h);13==a&&(ma(b,"id",d),d=d||"-",$(b).ga(d));c[a]=d};b.g=function(a,b){return a in c?c[a]:b};var d;b.ia=function(){d=s(ta(X,b),200)};b.F=function(){A(b.k);
A(d)}}function X(a,b,c){a&&a.call&&(c=a,a=n);b&&b.call&&(c=b,b=n);var d=this,e=ya(d,a,b),k=za(d),f=d.i===n&&!k.J;b=d.O=$(d);var g=Aa(),x=aa(),I=d.g(5);b.U(1,f);A(d.k);d.n=0;d.j=0;ba(d);!d.g(9)&&e.W||e.V||t&&"preview"==t.loadPurpose||g.f.D&&g.f.w&&10>g.f.D&&10>g.f.w||(d.B=x.m,d.A=x.l,e={cs:g.Q,cd:g.P,fl:g.T,je:g.X,la:g.Y,sw:g.f.D,sh:g.f.w,dp:g.S,pu:e.ja,pt:e.ha||"-",ri:k.J,ru:k.ea,re:b.fa,vi:b.t,pv:b.p,lv:b.Z,vw:x.N,vh:x.L,dw:x.I,dh:x.H,st:x.m,sl:x.l,un:d.g(3),pp:b.ca(),ec:I,aip:d.g(2)?1:n,tz:g.$},
d.h&&la(d.h,e),q&&(d.uid=b.c,e.bc=1),K?(e.o_si=K,e.o_vi=ca,e.o_ci=da):d.K=1,d.ba=0,Q(d,"pv",e,function(a){a!==n&&(d.i=a,A(d.k),d.k=s(r(R,d),5E3),c&&c())},5),d.i!==n?a!==n&&(d.i=n):(s(r(Ba,d),500),B(l,"beforeunload",r(Ca,d))))}function Y(a,b,c){G(a,"Event name is required");b&&b.call&&(c=b,b=n);if(b===""+b||b===+b)b={caption:b};b=va(b||{});b.gs_evt_name=a;R(this,"event",b,c)}function R(a,b,c,d){if(a.i!==n){if(!c){var e=aa();c={vw:e.N,vh:e.L,dw:e.I,dh:e.H,st:e.m,sl:e.l,mst:a.B,msl:a.A}}c.i=a.i;c.e=
b;c.et=Da(a);q&&(c.bc=1);a.K&&K&&(a.K=0,c.o_si=K,c.o_vi=ca,c.o_ci=da);Q(a,"ping",c,function(){d&&d();A(a.k);a.k=s(r(R,a),[7E3,12E3][a.ba++]||17500+5E3*O.random())},5)}else s(function(){R(a,b,c,d)},5E3)}function na(a){var b=a.h;if(a.i!==n){var c={};la(b,c);Q(a,"prop",c,r,5)}else s(function(){na(a)},5E3)}function oa(){var a=l.olark;a&&a("api.boot.onIdentityReady",function(a,c,d){K=a;ca=c;da=d})}function Q(a,b,c,d,e){var k=s(function(){g&&g();ea=(ea+1)%fa[D];c.et&&(c.et=0);c.rt=1;--e&&Q(a,b,c,d,e)},
1E4),f=$(a);c.cb=Ea(function(a){d(a);g&&g();A(k)});c.a=a.b;c.au=a.g(14);c.id=f.c;c.cid=f.M;c.tv=ha;var f=b+"?"+W(c),g;pa?pa.ka(f):g=Fa(f)}function Fa(a){var b=h[ja]("head")[0],c=h[ia]("script");c.src=(Ga?"https":"http")+"://"+fa[ea]+a;b.appendChild(c);return function(){c&&b.removeChild(c);c=null}}function Ea(a){var b="_"+Ha++;P[b]=a;return b}function L(a){function b(){var a=e[u];a&&(e[u]=a[v](c)[0])}var c=":_GS_:",d;if(L[a])return L[a];var e=l.top;L[a]=d={R:function(){b();e[u]=(e[u]||"")+c+[a,d.c,
d.C]}};try{var k=e[u]||"";if(-1!=k[U](c)){var f=k[v](c)[1][v](",");f[0]==a&&(d.c=f[1]||"",d.C=f[2]||"")}b()}catch(g){e={}}return d}function ya(a,b,c){var d=h[ia]("a");d.href=b||l.location.href;b=d.href;a.g(7,1)||(b=b[S](/\?[^#]*/,""));a.g(8)||(b=b[S](/#.*$/,""));return{ja:b,ha:c!==n?c:h.title,W:/^file:/.test(b)||/\/\/localhost[\/:]/.test(b+"/"),V:/fb_xd_(bust|fragment)/.test(b)}}function Aa(){var a,b,c,d,e,k,f=0,g=0;F&&(f=F.width,g=F.height);e=(e=l.orientation)&&(e+360)%180;return{f:{D:e?g:f,w:e?
f:g},P:F&&F.colorDepth||"-",Y:(t.language||t.browserLanguage||"-")[T](),X:+!!t.javaEnabled(),Q:h.characterSet||h.charSet||"-",T:function(f,g){if(t&&(a=t.plugins)&&0<(b=a[D]))for(e=0;e<b;e++){if(-1<(d=a[e])[u][U](c=f+" "+g))return c=d.description[v](c+" "),c[1]}else if(k=l.ActiveXObject){try{if(d=(new k((c=f+g+".")+f+g)).GetVariable("$version"))return d=d[v](" ")[1][v](","),d[0]+"."+d[1]+" r"+d[2]}catch(y){}for(e=13;--e;)try{if(d=(d=new k(c+c+e))&&1)return e+".0"}catch(n){}}return"-"}("Shockwave",
"Flash"),S:l.devicePixelRatio||1,$:(new w).getTimezoneOffset()}}function aa(){function a(a){return l["inner"+a]||c&&c[e="client"+a]||d&&d[e]}function b(a){return O.max(d[e="scroll"+a]||0,c[e]||0,d[e="offset"+a],c[e],d[e="client"+a],c[e])}var c=h.documentElement,d=h.body||c,e;return{N:a("Width"),L:a("Height"),I:b("Width"),H:b("Height"),l:l.pageXOffset||c&&c.scrollLeft||0,m:l.pageYOffset||c&&c.scrollTop||0}}function qa(a){a.j&&(a.j=0,a.n=new w-a.u+(a.n||0))}function ba(a){A(a.aa);a.aa=s(r(qa,a),15E3);
a.j||(a.j=1,a.u=new w)}function Da(a){var b=a.n,c=new w;a.j&&(b+=c-a.u,a.u=c);a.n=0;return b}function Ia(a){ba(a);var b=aa();b.m>a.B&&(a.B=b.m);b.l>a.A&&(a.A=b.l)}function Ba(a){var b=r(ba,a);B(h,"mousemove",b);B(h,"keydown",b);B(l,"scroll",r(Ia,a));B(h,"focus",b,"focusin");B(h,"blur",r(qa,a),"focusout")}function za(a){a=a.g(10,h.referrer);var b;!a||/^(chrome|about|file):/.test(a)||/^\[.*\]$/.test(a)?a="-":b=a[S](/^.*?\/\//,"")[U](location.host);return{J:+(0<=b&&8>=b),ea:a}}function Ca(a){if(a.i!==
n){var b=Z(a);a.g(1,1)?b.r("gs_p_"+a.b,a.i):(b=L(a.b),b.C=a.i,b.R())}}function $(a){function b(){y.r(h,l.c=[q,z.t*f+e,z.p*g+k,+new w].join(":"));a.s(11,q)}function c(){p&&"-"!==p?y.r(I,p):y.G(I)}function d(a){p=z.M=a;c()}var e=2019,k=4621,f=548,g=379,h="gs_u_"+a.b,I="gs_v_"+a.b,y=Z(a,1),l=L(a.b),m=(y.o(h)||l.c||"")[v](":"),r=1,q=a.g(11,m[0])||(r=0,ua()),s=((m[1]||e)-e)/f,u=((m[2]||k)-k)/g,m=(m[3]||0)/1E3,p=a.g(13),t=y.o(I),z={c:q,M:p,t:s,p:u,Z:~~m,fa:r,U:function(a,c){z.p+=+a;z.t+=+c;b()},ga:d,ma:b,
ca:function(){var b=y.o("gs_p_"+a.b)||l.C;y.G("gs_p_"+a.b);return a.i!==n?a.i:b}};t&&!p&&d(t);p&&c();return z}function wa(a,b,c,d){function e(a,b){b=b||(E(a)?a:{});E(a)||(b[u]=a);G(b[u],"No Name");g.push(b);return h}function k(a){for(var b=0;b<a[D];)e(a[b++]);return h}function f(){J(function(){var a=Z(this,1),d="gs_t_"+this.b,e=a.o(d)||0;a.r(d,+new w);Y.call(this,"_transaction",{d:JSON.stringify({id:b,pt:{ts:+e},i:g,d:c})})},a)}!c&&E(b)&&(c=b,b=c.id);G(b,"No ID");var g=[];d&&k(d);c&&c.track&&f();
var h={id:b,addItem:e,addItems:k,track:f};return h}function xa(a,b){!b&&E(a)&&(b=a,a=b.id);G(a,"ID is required");this.s(13,a);b&&this.s(4,b)}var n,M,N=l._gs||(M=1,function(){ra.push(arguments)}),ra=N.q=N.q||[];if(!N.v){var m={},q=l.GoSquared;if(q){C(q,function(a,b){"acct"==b?(V(a,"_default",1),N(function(){function c(a){d[a.shift()].apply(d,a)}var d=q.DefaultTracker=m._default;if(b=q.q)for(;a=b.shift();)c(a);q.q={push:c};(b=q.load)&&b(d)})):"load"!=b&&"q"!=b&&N("set",b,a)});var p=ka.prototype;p.TrackView=
X;p.TrackEvent=Y;p.Cancel=function(){this.F()};q.Tracker=V;q.Cancel=r(H,"cancel")}var K,ca,da,fa=["data.gosquared.com/","data2.gosquared.com/"],ea=0|O.random()*fa[D],Ga=/^https:/.test(location.href),pa,P={},Ha=0;l._gs=H;for(H.v=ha;p=ra.shift();)H.apply({},p);if(M){M=h[ja]("script");for(var p=M[D],sa;p--;)(sa=M[p].getAttribute("data-gs"))&&H(sa)}oa();B(l,"load",oa)}})(window,document,navigator||{},screen,Math,Date,setTimeout,clearTimeout,encodeURIComponent,"6.1.1588","createElement","split","replace",
"length","toLowerCase","name","getElementsByTagName","indexOf");
